// <auto-generated />
using ElectricityDataApp.Persistence.Repository.UnitOfWork;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectricityDataApp.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20230524184719_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectricityDataApp.Models.RegionElectricityConsumptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChainRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SumPMinus")
                        .HasColumnType("float");

                    b.Property<double>("SumPPlus")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("RegionElectricityConsumptions");
                });
#pragma warning restore 612, 618
        }
    }
}
